//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "IPS.UMLSPF.UMLSPFDiagram")]

namespace IPS.UMLSPF
{
	/// <summary>
	/// DomainClass UMLSPFDiagram
	/// Description for IPS.UMLSPF.UMLSPFDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("IPS.UMLSPF.UMLSPFDiagram.DisplayName", typeof(global::IPS.UMLSPF.UMLSPFDomainModel), "IPS.UMLSPF.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("IPS.UMLSPF.UMLSPFDiagram.Description", typeof(global::IPS.UMLSPF.UMLSPFDomainModel), "IPS.UMLSPF.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::IPS.UMLSPF.UMLSPFDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("f1ee146e-d981-4262-8e9d-ddacc33d3420")]
	public partial class UMLSPFDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::IPS.UMLSPF.UMLSPFToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Diagram styles
		/// <summary>
		/// Initializes style set resources for this shape type
		/// </summary>
		/// <param name="classStyleSet">The style set for this shape class</param>
		protected override void InitializeResources(DslDiagrams::StyleSet classStyleSet)
		{
			base.InitializeResources(classStyleSet);
			
			// Fill brush settings for this shape.
			DslDiagrams::BrushSettings backgroundBrush = new DslDiagrams::BrushSettings();
			backgroundBrush.Color = global::System.Drawing.Color.FromKnownColor(global::System.Drawing.KnownColor.DimGray);
			classStyleSet.OverrideBrush(DslDiagrams::DiagramBrushes.DiagramBackground, backgroundBrush);
		
			// Text brush settings for this shape.
			DslDiagrams::BrushSettings textBrush = new DslDiagrams::BrushSettings();
			textBrush.Color = global::System.Drawing.Color.FromKnownColor(global::System.Drawing.KnownColor.White);
			classStyleSet.OverrideBrush(DslDiagrams::DiagramBrushes.DiagramText, textBrush);
		
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::IPS.UMLSPF.ClaseEnriquecida)
			{
				global::IPS.UMLSPF.ShapeClaseEnriquecida newShape = new global::IPS.UMLSPF.ShapeClaseEnriquecida(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.UMLSPF.Herencia)
			{
				global::IPS.UMLSPF.IMGHerencia newShape = new global::IPS.UMLSPF.IMGHerencia(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.UMLSPF.Operaciones)
			{
				global::IPS.UMLSPF.ShapeOperaciones newShape = new global::IPS.UMLSPF.ShapeOperaciones(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.UMLSPF.Clase)
			{
				global::IPS.UMLSPF.ShapeClase newShape = new global::IPS.UMLSPF.ShapeClase(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.UMLSPF.Parametros)
			{
				global::IPS.UMLSPF.ShapeParametro newShape = new global::IPS.UMLSPF.ShapeParametro(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.UMLSPF.AtributoIdentificador)
			{
				global::IPS.UMLSPF.ShapeAtributoID newShape = new global::IPS.UMLSPF.ShapeAtributoID(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.UMLSPF.Atributo)
			{
				global::IPS.UMLSPF.ShapeAtributo newShape = new global::IPS.UMLSPF.ShapeAtributo(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.UMLSPF.EstilosClase)
			{
				global::IPS.UMLSPF.ShapeEstiloClase newShape = new global::IPS.UMLSPF.ShapeEstiloClase(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.UMLSPF.EstiloAtributos)
			{
				global::IPS.UMLSPF.ShapeEstiloAtributos newShape = new global::IPS.UMLSPF.ShapeEstiloAtributos(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.UMLSPF.EstiloMetodos)
			{
				global::IPS.UMLSPF.ShapeEstiloMetodos newShape = new global::IPS.UMLSPF.ShapeEstiloMetodos(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::IPS.UMLSPF.conAsociacion)
			{
				global::IPS.UMLSPF.ConecClase newShape = new global::IPS.UMLSPF.ConecClase(this.Partition);
				return newShape;
			}
			if(element is global::IPS.UMLSPF.EsPadre)
			{
				global::IPS.UMLSPF.ConEsPadre newShape = new global::IPS.UMLSPF.ConEsPadre(this.Partition);
				return newShape;
			}
			if(element is global::IPS.UMLSPF.EsHija)
			{
				global::IPS.UMLSPF.ConEsHijo newShape = new global::IPS.UMLSPF.ConEsHijo(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::IPS.UMLSPF.ShapeOperaciones.DecoratorsInitialized += ShapeOperacionesDecoratorMap.OnDecoratorsInitialized;
			global::IPS.UMLSPF.ShapeClase.DecoratorsInitialized += ShapeClaseDecoratorMap.OnDecoratorsInitialized;
			global::IPS.UMLSPF.ShapeParametro.DecoratorsInitialized += ShapeParametroDecoratorMap.OnDecoratorsInitialized;
			global::IPS.UMLSPF.ShapeAtributoID.DecoratorsInitialized += ShapeAtributoIDDecoratorMap.OnDecoratorsInitialized;
			global::IPS.UMLSPF.ShapeAtributo.DecoratorsInitialized += ShapeAtributoDecoratorMap.OnDecoratorsInitialized;
			global::IPS.UMLSPF.ShapeClaseEnriquecida.DecoratorsInitialized += ShapeClaseEnriquecidaDecoratorMap.OnDecoratorsInitialized;
			global::IPS.UMLSPF.ShapeEstiloClase.DecoratorsInitialized += ShapeEstiloClaseDecoratorMap.OnDecoratorsInitialized;
			global::IPS.UMLSPF.ShapeEstiloAtributos.DecoratorsInitialized += ShapeEstiloAtributosDecoratorMap.OnDecoratorsInitialized;
			global::IPS.UMLSPF.ShapeEstiloMetodos.DecoratorsInitialized += ShapeEstiloMetodosDecoratorMap.OnDecoratorsInitialized;
			global::IPS.UMLSPF.ConecClase.DecoratorsInitialized += ConecClaseDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ShapeOperaciones.
		/// </summary>
		internal static partial class ShapeOperacionesDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ShapeOperaciones.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.Operaciones.MostrarOperacionDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NombreOperacion").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ShapeClase.
		/// </summary>
		internal static partial class ShapeClaseDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ShapeClase.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.Clase.NombreClaseDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NombreClase").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ShapeParametro.
		/// </summary>
		internal static partial class ShapeParametroDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ShapeParametro.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.Parametros.MostrarParametroDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "MostrarParametros").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ShapeAtributoID.
		/// </summary>
		internal static partial class ShapeAtributoIDDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ShapeAtributoID.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.AtributoIdentificador.MostrarAtributoIDDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "MostrarAtributoID").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ShapeAtributo.
		/// </summary>
		internal static partial class ShapeAtributoDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ShapeAtributo.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.Atributo.MostrarAtributoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "MostrarAtributo").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ShapeClaseEnriquecida.
		/// </summary>
		internal static partial class ShapeClaseEnriquecidaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ShapeClaseEnriquecida.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.Clase.NombreClaseDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Nombre").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ShapeEstiloClase.
		/// </summary>
		internal static partial class ShapeEstiloClaseDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ShapeEstiloClase.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.EstilosClase.MostrarEstilosClaseDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Mostrar").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ShapeEstiloAtributos.
		/// </summary>
		internal static partial class ShapeEstiloAtributosDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ShapeEstiloAtributos.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.EstiloAtributos.MostrarEADomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Mostrar").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.EstiloAtributos.MostrarEADomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Mostrar").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ShapeEstiloMetodos.
		/// </summary>
		internal static partial class ShapeEstiloMetodosDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ShapeEstiloMetodos.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.EstiloMetodos.MostrarEMDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Mostrar").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.EstiloMetodos.MostrarEMDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Mostrar").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for ConecClase.
		/// </summary>
		internal static partial class ConecClaseDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for ConecClase.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.conAsociacion.refDDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "refDCL").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.conAsociacion.refIDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "refICL").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.conAsociacion.NombreRelacionDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NombreRelacionDE").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.conAsociacion.NameRelationDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "NombreRelacionIZ").AssociateValueWith(shape.Store, propertyInfo);
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::IPS.UMLSPF.conAsociacion.ConexionTipoDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "RelacionTipo").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::IPS.UMLSPF.ConectarClasesConnectAction conectarClasesConnectAction;
		private global::IPS.UMLSPF.ConectarPadreConnectAction conectarPadreConnectAction;
		private global::IPS.UMLSPF.ConectarHijoConnectAction conectarHijoConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::IPS.UMLSPF.UMLSPFToolboxHelper.ConectarClasesFilterString))
				{
					if (this.conectarClasesConnectAction == null)
					{
						this.conectarClasesConnectAction = new global::IPS.UMLSPF.ConectarClasesConnectAction(this);
						this.conectarClasesConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.conectarClasesConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::IPS.UMLSPF.UMLSPFToolboxHelper.ConectarPadreFilterString))
				{
					if (this.conectarPadreConnectAction == null)
					{
						this.conectarPadreConnectAction = new global::IPS.UMLSPF.ConectarPadreConnectAction(this);
						this.conectarPadreConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.conectarPadreConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::IPS.UMLSPF.UMLSPFToolboxHelper.ConectarHijoFilterString))
				{
					if (this.conectarHijoConnectAction == null)
					{
						this.conectarHijoConnectAction = new global::IPS.UMLSPF.ConectarHijoConnectAction(this);
						this.conectarHijoConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.conectarHijoConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.conectarClasesConnectAction != null)
					{
						this.conectarClasesConnectAction.Dispose();
						this.conectarClasesConnectAction = null;
					}
					if(this.conectarPadreConnectAction != null)
					{
						this.conectarPadreConnectAction.Dispose();
						this.conectarPadreConnectAction = null;
					}
					if(this.conectarHijoConnectAction != null)
					{
						this.conectarHijoConnectAction.Dispose();
						this.conectarHijoConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// UMLSPFDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xf1ee146e, 0xd981, 0x4262, 0x8e, 0x9d, 0xdd, 0xac, 0xc3, 0x3d, 0x34, 0x20);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public UMLSPFDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public UMLSPFDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace IPS.UMLSPF
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.ClaseEnriquecida), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.Herencia), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.Operaciones), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.Clase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.Parametros), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.AtributoIdentificador), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.Atributo), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.EstilosClase), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.EstiloAtributos), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.EstiloMetodos), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.conAsociacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.EsPadre), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.EsHija), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::IPS.UMLSPF.ClaseEnriquecida)
				{
					parentElement = GetParentForClaseEnriquecida((global::IPS.UMLSPF.ClaseEnriquecida)childElement);
				} else
				if(childElement is global::IPS.UMLSPF.Herencia)
				{
					parentElement = GetParentForHerencia((global::IPS.UMLSPF.Herencia)childElement);
				} else
				if(childElement is global::IPS.UMLSPF.Operaciones)
				{
					parentElement = GetParentForOperaciones((global::IPS.UMLSPF.Operaciones)childElement);
				} else
				if(childElement is global::IPS.UMLSPF.Clase)
				{
					parentElement = GetParentForClase((global::IPS.UMLSPF.Clase)childElement);
				} else
				if(childElement is global::IPS.UMLSPF.Parametros)
				{
					parentElement = GetParentForParametros((global::IPS.UMLSPF.Parametros)childElement);
				} else
				if(childElement is global::IPS.UMLSPF.AtributoIdentificador)
				{
					parentElement = GetParentForAtributoIdentificador((global::IPS.UMLSPF.AtributoIdentificador)childElement);
				} else
				if(childElement is global::IPS.UMLSPF.Atributo)
				{
					parentElement = GetParentForAtributo((global::IPS.UMLSPF.Atributo)childElement);
				} else
				if(childElement is global::IPS.UMLSPF.EstilosClase)
				{
					parentElement = GetParentForEstilosClase((global::IPS.UMLSPF.EstilosClase)childElement);
				} else
				if(childElement is global::IPS.UMLSPF.EstiloAtributos)
				{
					parentElement = GetParentForEstiloAtributos((global::IPS.UMLSPF.EstiloAtributos)childElement);
				} else
				if(childElement is global::IPS.UMLSPF.EstiloMetodos)
				{
					parentElement = GetParentForEstiloMetodos((global::IPS.UMLSPF.EstiloMetodos)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::IPS.UMLSPF.ModeloClassWEB GetParentForHerencia( global::IPS.UMLSPF.Herencia root )
			{
				// Segments 0 and 1
				global::IPS.UMLSPF.ModeloClassWEB result = root.ModeloClassWEB;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.UMLSPF.ModeloClassWEB GetParentForOperaciones( global::IPS.UMLSPF.Operaciones root )
			{
				// Segments 0 and 1
				global::IPS.UMLSPF.Clase root2 = root.Clase;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::IPS.UMLSPF.ModeloClassWEB result = root2.ModeloClassWEB;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.UMLSPF.ModeloClassWEB GetParentForClase( global::IPS.UMLSPF.Clase root )
			{
				// Segments 0 and 1
				global::IPS.UMLSPF.ModeloClassWEB result = root.ModeloClassWEB;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.UMLSPF.ModeloClassWEB GetParentForParametros( global::IPS.UMLSPF.Parametros root )
			{
				// Segments 0 and 1
				global::IPS.UMLSPF.Operaciones root2 = root.Operaciones;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::IPS.UMLSPF.Clase root4 = root2.Clase;
				if ( root4 == null ) return null;
				// Segments 4 and 5
				global::IPS.UMLSPF.ModeloClassWEB result = root4.ModeloClassWEB;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.UMLSPF.ModeloClassWEB GetParentForAtributoIdentificador( global::IPS.UMLSPF.AtributoIdentificador root )
			{
				// Segments 0 and 1
				global::IPS.UMLSPF.Clase root2 = root.Clase;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::IPS.UMLSPF.ModeloClassWEB result = root2.ModeloClassWEB;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.UMLSPF.ModeloClassWEB GetParentForAtributo( global::IPS.UMLSPF.Atributo root )
			{
				// Segments 0 and 1
				global::IPS.UMLSPF.Clase root2 = root.Clase;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::IPS.UMLSPF.ModeloClassWEB result = root2.ModeloClassWEB;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.UMLSPF.ModeloClassWEB GetParentForClaseEnriquecida( global::IPS.UMLSPF.Clase root )
			{
				// Segments 0 and 1
				global::IPS.UMLSPF.ModeloClassWEB result = root.ModeloClassWEB;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.UMLSPF.ModeloClassWEB GetParentForEstilosClase( global::IPS.UMLSPF.EstilosClase root )
			{
				// Segments 0 and 1
				global::IPS.UMLSPF.Clase root2 = root.ClaseEnriquecida as global::IPS.UMLSPF.Clase;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::IPS.UMLSPF.ModeloClassWEB result = root2.ModeloClassWEB;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.UMLSPF.ModeloClassWEB GetParentForEstiloAtributos( global::IPS.UMLSPF.EstiloAtributos root )
			{
				// Segments 0 and 1
				global::IPS.UMLSPF.Clase root2 = root.ClaseEnriquecida as global::IPS.UMLSPF.Clase;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::IPS.UMLSPF.ModeloClassWEB result = root2.ModeloClassWEB;
				if ( result == null ) return null;
				return result;
			}
			public static global::IPS.UMLSPF.ModeloClassWEB GetParentForEstiloMetodos( global::IPS.UMLSPF.EstiloMetodos root )
			{
				// Segments 0 and 1
				global::IPS.UMLSPF.Clase root2 = root.ClaseEnriquecida as global::IPS.UMLSPF.Clase;
				if ( root2 == null ) return null;
				// Segments 2 and 3
				global::IPS.UMLSPF.ModeloClassWEB result = root2.ModeloClassWEB;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.conAsociacion), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::IPS.UMLSPF.conAsociacion.refDDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::IPS.UMLSPF.ConecClase.FindConecClaseDecorator("refDCL");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::IPS.UMLSPF.conAsociacion.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::IPS.UMLSPF.conAsociacion.refIDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::IPS.UMLSPF.ConecClase.FindConecClaseDecorator("refICL");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::IPS.UMLSPF.conAsociacion.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::IPS.UMLSPF.conAsociacion.NombreRelacionDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::IPS.UMLSPF.ConecClase.FindConecClaseDecorator("NombreRelacionDE");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::IPS.UMLSPF.conAsociacion.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::IPS.UMLSPF.conAsociacion.NameRelationDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::IPS.UMLSPF.ConecClase.FindConecClaseDecorator("NombreRelacionIZ");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::IPS.UMLSPF.conAsociacion.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::IPS.UMLSPF.conAsociacion.ConexionTipoDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::IPS.UMLSPF.ConecClase.FindConecClaseDecorator("RelacionTipo");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::IPS.UMLSPF.conAsociacion.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.conAsociacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.EsPadre), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::IPS.UMLSPF.EsHija), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::IPS.UMLSPF.UMLSPFDiagram diagram = linkShape.Diagram as global::IPS.UMLSPF.UMLSPFDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
