//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPS.UMLSPF
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "kacqSPF";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"UMLSPF";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"IPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID UMLSPFDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(UMLSPFCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID UMLSPFExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(UMLSPFCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewUMLSPFExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(UMLSPFCommandSetId), 0x0001);
	
		// Package identifier
		public const string UMLSPFPackageId = "8212dcc1-81c2-480c-9772-e73f24604d12";
		
		// Editor factory identifier
		public const string UMLSPFEditorFactoryId = "096cb769-d340-4d6e-b06a-a2816f59d3a1";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string UMLSPFModelExplorerToolWindowId = "77ad4da6-9fa1-444f-91bd-643da7ca02ae";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace IPS.UMLSPF
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string UMLSPFCommandSetId = "59b664ec-8421-4f60-b369-1243bc3656cd";
	}
}